# Generated by Django 2.0.3 on 2018-03-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=4)),
                ('student_name', models.CharField(max_length=16)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
